= Insecure HTTPS4 Demo

This project uses https://github.com/kameshsampath/camel-insecurehttps4[camel-insecurehttps4] custom https4 component

== Running

Clone the project locally and run using `./mvnw clean install camel:run`

== Dependencies

To use the project as is requires a https service running on port *8443*,
you can use this https://github.com/kameshsampath/secured-calculator[secured-calculator] or
https://docs.nodejitsu.com/articles/HTTP/servers/how-to-create-a-HTTPS-server/

== License

Copyright 2017 Kamesh Sampath<kamesh.sampath@hotmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.